name: mercado_pago_mobile_checkout
description: Mercado Pago's Unofficial Flutter checkout library that implements the MercadoPago Mobile Checkout using the native SDK.
version: 0.0.2
author: Ricardo Markiewicz <ricardo.markiewicz@gmail.com>
homepage: https://github.com/Gazer/px-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  freezed: ^0.12.5
  json_serializable: ^3.5.1

flutter:
  plugin:
    platforms:
      android:
        package: ar.com.p39.mercado_pago_mobile_checkout
        pluginClass: MercadoPagoMobileCheckoutPlugin
      ios:
        pluginClass: MercadoPagoMobileCheckoutPlugin

